title: PersAI lab
email: ssahebi@albany.edu
description: Personalized Artificial Intelligence Lab at SUNY-Albany
show_downloads: true
github_username: persai-lab
google_analytics:
theme: minima
# twitter_username: 


#plugins:
- jekyll-seo-tag
#  - jekyll-redirect-from
# - jekyll-feed